### ISSUE TITLE
Comment at end of file causes panic

### ISSUE THREAD

**Issue by korylprince** [josharian/impl#50]
You can reproduce this issue with the following `main.go` file:

```go
package main

type T struct{}

type Interface interface {
	// Func comment
	Func()
}

// end comment
```

Then run:

```bash
$ impl 't T' Interface
panic: flattenCommentMap expects comment map of length 1

goroutine 1 [running]:
main.flattenCommentMap(0xc000015fb0?)
	/home/administrator/code/go/src/github.com/josharian/impl/impl.go:410 +0x44b
main.Pkg.funcsig({0xc000045000?, 0xc00007efc0?, {0xc00001e9c0?, 0xc00007eb80?}}, 0xc00007f0c0, 0xc00017beb8?, 0x1)
	/home/administrator/code/go/src/github.com/josharian/impl/impl.go:277 +0x1ab
main.funcs({0x7ffd5e6b88fa, 0x9}, {0xc00001e034, 0x9}, {0xc00001e9c0, 0x4}, 0x28?)
	/home/administrator/code/go/src/github.com/josharian/impl/impl.go:331 +0x3cb
main.main()
	/home/administrator/code/go/src/github.com/josharian/impl/impl.go:485 +0x2ad
````

Removing the last comment or putting any non-comment code after it causes the panic not to happen.

**Comment by josharian** [comment]
Well that's entertaining. Thanks for the report.
